### ISSUE TITLE
Not able to build on M1 chip

### ISSUE THREAD

**Issue by filippoweb3** [Kalapaja/kampela-firmware#23] opened 2024-01-22 14:49 UTC
I am trying to follow the guidelines to build the rust code in release mode, but I am getting the error below

![Screenshot 2024-01-22 at 15 48 31](https://github.com/Kalapaja/kampela-firmware/assets/110459737/5b4083e1-6b96-48d1-b814-15f364dfc11b)

**Comment by Slesarew** [comment] 2024-01-23 14:20
Looks like upstream issue with secp256k1. We don't have an M1 here to reproduce and figure this out yet. This will probably have to wait quite a bit, until we or upstream Substrate changes to more native crate instead of this wrapper, or someone with M1 figures out how to cross-compile this. The focus now is on making this buildable on more popular embedded dev architectures.

**Comment by Vovke** [comment] 2024-01-23 15:42
Hey @filippoweb3
it might be an issue with the `arm-none-eabi-gcc` provided by brew, if you got the compiler by running `brew install arm-none-eabi-gcc` uninstall it.
you can get compiler from here https://developer.arm.com/downloads/-/gnu-rm  (that worked for me) alternatively it should also work with brew if you install whole toolchain, try `brew install --cask gcc-arm-embedded`

**Comment by Vovke** [comment] 2024-01-24 14:47
addressed in #24

**Comment by filippoweb3** [comment] 2024-01-24 15:47
@Vovke thanks! I was able to build the code and the install it on the Kampela signer. However the rust code compiled with many warnings. Let me know if you want me to share the info here.

**Comment by Vovke** [comment] 2024-01-24 16:08
> @Vovke thanks! I was able to build the code and the install it on the Kampela signer. However the rust code compiled with many warnings. Let me know if you want me to share the info here.

no need, those are low prio and not macos related. we will get them resolved after more urgent once! Thanks for pointing out blocking issue!

**Closed** 2024-01-24 19:17 UTC
